all:
  stylesheets: [http://yui.yahooapis.com/combo?3.2.0/build/cssreset/reset-min.css&3.2.0/build/cssfonts/fonts-min.css&3.2.0/build/cssbase/base-min.css]
  javascripts: [http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js]